version: "3.3"
services:
  app:
    container_name: backup-server
    image: "backup-server:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RESTIC_PASSWORD: "my super secret passphrase"
      RESTIC_REPOSITORY: "/backup" # Use "b2:bucket-name:/" in prod
#      B2_ACCOUNT_ID: "XXX" # Prod only
#      B2_ACCOUNT_KEY: "YYY" # Prod only
      SCHEDULE: "* * * * *"
      CAPROVER_URL: "https://captain.xxx.yyy.zzz"
      CAPROVER_PASSWORD: "my super secret caprover password"
    volumes:
      - ./mocks/volumes:/volumes # Use /var/lib/docker/volumes in prod
      - ./mocks/captain:/captain # Use /captain in prod
      - ./mocks/backup:/backup # Only for debug purposes
volumes:
  app: