version: "3.3"
services:
  app:
    container_name: backup-server
    image: "backup-server:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RESTIC_PASSWORD: "my super secret passphrase"
      RESTIC_REPOSITORY: "/backup" # Use "b2:bucket-name:/" in prod
      BACKUP_CRON: "* * * * *"
      BACKUP_DURATION: "0y1m0d0h" # Optional
      CAP_ROVER_URL: "https://captain.xxx.yyy.zzz"
      CAP_ROVER_PASSWORD: "my super secret caprover password"
      #      B2_ACCOUNT_ID: "XXX" # Prod only
      #      B2_ACCOUNT_KEY: "YYY" # Prod only
    volumes:
      - ./mocks/volumes:/volumes # Use /var/lib/docker/volumes in prod
      - ./mocks/captain:/captain # Use /captain in prod
      - ./mocks/backup:/backup # Only for debug purposes
volumes:
  app: